#!/usr/bin/env bash
# Build an installable Android APK locally, without EAS servers.
#
#   npm run build:apk          # release APK (debug-keystore signed, sideloadable)
#   npm run build:apk -- debug # debug APK
#
# Requirements: JDK 17+, Android SDK (ANDROID_HOME or ANDROID_SDK_ROOT set).
# The native android/ project is generated by `expo prebuild` and is gitignored,
# so it is regenerated from app.json on every run.
set -euo pipefail

VARIANT="${1:-release}"
case "$VARIANT" in
  release|debug) ;;
  *) echo "Unknown variant '$VARIANT' (expected 'release' or 'debug')" >&2; exit 1 ;;
esac

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if [ -z "${ANDROID_HOME:-}" ] && [ -z "${ANDROID_SDK_ROOT:-}" ]; then
  echo "ANDROID_HOME / ANDROID_SDK_ROOT is not set — install the Android SDK first." >&2
  echo "See https://docs.expo.dev/get-started/set-up-your-environment/ (Android Studio)." >&2
  exit 1
fi

if [ ! -d node_modules ]; then
  echo "==> Installing dependencies"
  npm ci
fi

echo "==> Generating the native Android project (expo prebuild)"
npx expo prebuild --platform android --clean --no-install

# Capitalize the variant for the Gradle task name: release -> assembleRelease.
TASK="assemble$(printf '%s' "${VARIANT:0:1}" | tr '[:lower:]' '[:upper:]')${VARIANT:1}"

echo "==> Running :app:$TASK"
(cd android && ./gradlew ":app:$TASK" --no-daemon)

mkdir -p build
APK="$(find "android/app/build/outputs/apk/$VARIANT" -name '*.apk' -print -quit)"
if [ -z "$APK" ]; then
  echo "Gradle finished but no APK was found under android/app/build/outputs/apk/$VARIANT" >&2
  exit 1
fi

OUT="build/local-news-$VARIANT.apk"
cp "$APK" "$OUT"
echo
echo "APK ready: $OUT"
echo "Install it with: adb install -r $OUT"
